version: '3.7'

services:
  geoserver:
    image: maxdragonheart/geoserver:${GEOSERVER_VERSION}
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GEOSERVER_VERSION: ${GEOSERVER_VERSION}
        HTTP_PORT: ${HTTP_PORT}
    container_name: geoserver
    restart: always
    ports:
    - ${HTTP_PORT}:8080
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

volumes:
  tomcat:
  geoserver:
