version: '3.7'

services:
  geoserver:
    image: maxdragonheart/dev-geoserver:${GS_VERSION}
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GS_VERSION: ${GS_VERSION}
        GS_DEMO_DATA: ${GS_DEMO_DATA}
        GS_HTTP_PORT: ${GS_HTTP_PORT}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
    container_name: dev_geoserver
    restart: always
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

  nginx:
    image: dev_geoserver/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: dev_nginx
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-log:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
#      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - 80:80
      - 443:443
    depends_on:
      - geoserver

volumes:
  tomcat:
  geoserver:
  nginx-conf:
  nginx-log:
  certbot-etc:
  certbot-var: