version: '3.7'

services:
  geoserver:
    image: dev_geoserver:dev
    build:
      context: ./geoserver
      dockerfile: Dockerfile
    container_name: dev_geoserver
    restart: always
    ports:
    - 8080:8080
    volumes:
    - tomcat-conf:/usr/local/tomcat/conf
    - geoserver-data:/var/geoserver

volumes:
  tomcat-conf:
  geoserver-data:
