version: '3.7'

services:
  geoserver:
    image: maxdragonheart/geoserver:latest
    environment:
      GS_VERSION: ${GS_VERSION}
      GS_HTTP_PORT: ${GS_HTTP_PORT}
      GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
      GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
    container_name: geoserver
    restart: always
    ports:
    - ${GS_HTTP_PORT}:8080
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

volumes:
  tomcat:
  geoserver:
