version: '3.7'

services:
  geoserver:
    image: maxdragonheart/staging-geoserver:${GS_VERSION}
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GS_VERSION: ${GS_VERSION}
        GS_DEMO_DATA: ${GS_DEMO_DATA}
        # GS_HTTP_PORT: ${GS_HTTP_PORT}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
        TOMCAT_MAJOR: ${TOMCAT_MAJOR}
        TOMCAT_MINOR: ${TOMCAT_MINOR}
        TOMCAT_PATCH: ${TOMCAT_PATCH}
    container_name: staging_geoserver
    restart: always
    ports:
    - 8080:8080
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

volumes:
  tomcat:
  geoserver:
