version: '3.7'

services:
  geoserver:
    image: drako-geoserver:dev
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GEOSERVER_VERSION: 2.20.1
        HTTP_PORT: 8081/tcp
    container_name: dev_geoserver
    restart: always
    command: sh -c "/opt/tomcat/bin/catalina.sh run"
    ports:
    - 8081:8080
    volumes:
    - tomcat-conf:/opt/tomcat/conf
    - tomcat-logs:/opt/tomcat/tomcat/logs
    - geoserver-data:/opt/tomcat/tomcat/webapps/geoserver/data
    - geoserver-customizations:/opt/tomcat/tomcat/webapps/geoserver/WEB-INF

volumes:
  tomcat-conf:
  tomcat-logs:
  geoserver-data:
  geoserver-customizations:
