version: '3.7'

services:
  geoserver:
    container_name: dev_geoserver
    image: dev_geoserver/geoserver
    build: ./geoserver
    restart: always
    ports:
    - 8080:8080
    volumes:
    - geoserver-data:/usr/local/tomcat/webapps/geoserver/data
    - geoserver-customizations:/usr/local/tomcat/webapps/geoserver/WEB-INF

volumes:
  geoserver-data:
  geoserver-customizations: