version: '3.7'

services:
  geoserver:
    image: gisconsultant/geoserver:${GEOSERVER_VERSION}
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GEOSERVER_VERSION: ${GEOSERVER_VERSION}
        HTTP_PORT: ${HTTP_PORT}
    container_name: geoserver
    restart: always
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

  nginx:
    image: gisconsultant/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-log:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
#      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - 80:80
      - 443:443
    depends_on:
      - geoserver

volumes:
  tomcat:
  geoserver:
  nginx-conf:
  nginx-log:
  certbot-etc:
  certbot-var: