version: '3.7'

services:
  geoserver:
    image: maxdragonheart/dev-geoserver:${GEOSERVER_VERSION}
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        GS_VERSION: ${GS_VERSION}
        GS_HTTP_PORT: ${GS_HTTP_PORT}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
    container_name: dev_geoserver
    restart: always
    ports:
    - ${GS_HTTP_PORT}:8080
    volumes:
    - tomcat:/opt/tomcat
    - geoserver:/opt/tomcat/webapps/geoserver

volumes:
  tomcat:
  geoserver:
