version: '3.7'

services:
  geoserver:
    container_name: dev_geoserver
    image: dev_geoserver/geoserver
    build: ./geoserver
    restart: always
    command: sh -c "/opt/tomcat/bin/catalina.sh run"
    ports:
    - 8080:8080
    volumes:
    - tomcat-conf:/opt/tomcat/conf
    - tomcat-logs:/opt/tomcat/tomcat/logs
    - geoserver-data:/opt/tomcat/tomcat/webapps/geoserver/data
    - geoserver-customizations:/opt/tomcat/tomcat/webapps/geoserver/WEB-INF

volumes:
  tomcat-conf:
  tomcat-logs:
  geoserver-data:
  geoserver-customizations:
