version: '3.7'

services:
  geoserver:
    image: maxdragonheart/staging-geoserver:${GS_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GS_VERSION: ${GS_VERSION}
        GS_DEMO_DATA: ${GS_DEMO_DATA}
        GS_HTTP_PORT: ${GS_HTTP_PORT}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
    container_name: staging_geoserver
    restart: always
    ports:
    #- 8080:8080
    - ${GS_HTTP_PORT}:8080
    volumes:
    - tomcat:/usr/local/tomcat
    - geoserver:/usr/local/tomcat/webapps/geoserver

volumes:
  tomcat:
  geoserver:
