version: '3.7'

services:
  geoserver:
    image: maxdragonheart/geoserver:${GS_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        GS_VERSION: ${GS_VERSION}
        GS_DEMO_DATA: ${GS_DEMO_DATA}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
    container_name: geoserver
    restart: always
    volumes:
    - tomcat:/usr/local/tomcat
    - geoserver:/usr/local/tomcat/webapps/geoserver

  nginx:
    image: maxdragonheart/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - nginx-conf:/etc/nginx
      - nginx-log:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - geoserver

volumes:
  tomcat:
  geoserver:
  nginx-conf:
  nginx-log:
  certbot-etc:
  certbot-var: